//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBPSetupGUI.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBPSetupGUI.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBP Launcher is currently running. Please close it and then run this again..
        /// </summary>
        public static string CBPLCurrentlyRunning {
            get {
                return ResourceManager.GetString("CBPLCurrentlyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this okay?.
        /// </summary>
        public static string ConsentIsCool {
            get {
                return ResourceManager.GetString("ConsentIsCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (close CBP Setup).
        /// </summary>
        public static string ConsentNo {
            get {
                return ResourceManager.GetString("ConsentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ConsentYes {
            get {
                return ResourceManager.GetString("ConsentYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying CBP Launcher into RoN root folder: .
        /// </summary>
        public static string CopyToRootError {
            get {
                return ResourceManager.GetString("CopyToRootError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the file update worked fine, deleting old files....
        /// </summary>
        public static string DeletingFiles {
            get {
                return ResourceManager.GetString("DeletingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the old files..
        /// </summary>
        public static string DeletingFilesError {
            get {
                return ResourceManager.GetString("DeletingFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language files look like they might be old. You can try running CBL Launcher to update them..
        /// </summary>
        public static string DLLDifference {
            get {
                return ResourceManager.GetString("DLLDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to try using the existing files?.
        /// </summary>
        public static string DLLOfferQuestion {
            get {
                return ResourceManager.GetString("DLLOfferQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking the language files..
        /// </summary>
        public static string DLLPathError {
            get {
                return ResourceManager.GetString("DLLPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The langauge files look up to date. Continuing....
        /// </summary>
        public static string DLLSame {
            get {
                return ResourceManager.GetString("DLLSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating the langauge files..
        /// </summary>
        public static string DLLUpdateFail {
            get {
                return ResourceManager.GetString("DLLUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language files updated..
        /// </summary>
        public static string DLLUpdateSuccess {
            get {
                return ResourceManager.GetString("DLLUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override language to English.
        /// </summary>
        public static string EnglishOverrideText {
            get {
                return ResourceManager.GetString("EnglishOverrideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like CBP Setup is already running in another thread..
        /// </summary>
        public static string ErrorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error replacing CBP Launcher with new version - file not found..
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error replacing CBP Launcher with new version - maybe old version was not deleted or wrong path?.
        /// </summary>
        public static string ErrorIO {
            get {
                return ResourceManager.GetString("ErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions error replacing CBP Launcher with new version. Try running CBP Setup as admin?.
        /// </summary>
        public static string ErrorPermissions {
            get {
                return ResourceManager.GetString("ErrorPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error replacing CBP Launcher with new version..
        /// </summary>
        public static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time run detected. An artificial delay has been added to messages so that they are easier to read. Afterwards, this will be disabled by default..
        /// </summary>
        public static string FirstTimeRun {
            get {
                return ResourceManager.GetString("FirstTimeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find CBP Launcher in RoN&apos;s root folder..
        /// </summary>
        public static string FoundRootNo {
            get {
                return ResourceManager.GetString("FoundRootNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found CBP Launcher in RoN&apos;s root folder..
        /// </summary>
        public static string FoundRootYes {
            get {
                return ResourceManager.GetString("FoundRootYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Current folder location is unrecognised..
        /// </summary>
        public static string LocationCase0 {
            get {
                return ResourceManager.GetString("LocationCase0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the root RoN folder..
        /// </summary>
        public static string LocationCase1 {
            get {
                return ResourceManager.GetString("LocationCase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the Workshop mods folder for normal CBP..
        /// </summary>
        public static string LocationCase2 {
            get {
                return ResourceManager.GetString("LocationCase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the local mods folder (it probably shouldn&apos;t be here except for testing)..
        /// </summary>
        public static string LocationCase3 {
            get {
                return ResourceManager.GetString("LocationCase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the Workshop mods folder for pre-release CBP..
        /// </summary>
        public static string LocationCase4 {
            get {
                return ResourceManager.GetString("LocationCase4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Location result unexpected..
        /// </summary>
        public static string LocationCaseDefault {
            get {
                return ResourceManager.GetString("LocationCaseDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when assigning paths. This window will close in 5 seconds..
        /// </summary>
        public static string LocationPathError {
            get {
                return ResourceManager.GetString("LocationPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to restore old versions....
        /// </summary>
        public static string OldVersionRestore {
            get {
                return ResourceManager.GetString("OldVersionRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restoring old versions: .
        /// </summary>
        public static string OldVersionRestoreError {
            get {
                return ResourceManager.GetString("OldVersionRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add artificial delay during process (to make reading easier).
        /// </summary>
        public static string SlowModeButtonText {
            get {
                return ResourceManager.GetString("SlowModeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done! Time to start CBP Launcher....
        /// </summary>
        public static string StartCBPL {
            get {
                return ResourceManager.GetString("StartCBPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBP Launcher is already running (maybe close it and run this again?)..
        /// </summary>
        public static string StartCBPLAlreadyRunning {
            get {
                return ResourceManager.GetString("StartCBPLAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like CBP Launcher didn&apos;t start :(.
        /// </summary>
        public static string StartCBPLFail {
            get {
                return ResourceManager.GetString("StartCBPLFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting CBP Launcher: .
        /// </summary>
        public static string StartCBPLProblem {
            get {
                return ResourceManager.GetString("StartCBPLProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBP Launcher detected as running; job complete..
        /// </summary>
        public static string StartCBPLSuccess {
            get {
                return ResourceManager.GetString("StartCBPLSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English text has been loaded..
        /// </summary>
        public static string StartupLanguageDetected {
            get {
                return ResourceManager.GetString("StartupLanguageDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBP Setup will prepare/update CBP Launcher..
        /// </summary>
        public static string StartupMessage {
            get {
                return ResourceManager.GetString("StartupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (User said no).
        /// </summary>
        public static string UserNo {
            get {
                return ResourceManager.GetString("UserNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (User said yes).
        /// </summary>
        public static string UserYes {
            get {
                return ResourceManager.GetString("UserYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBP Launcher in the RoN folder is not the same as the downloaded Workshop version. Updating it....
        /// </summary>
        public static string VersionCheckDifferent {
            get {
                return ResourceManager.GetString("VersionCheckDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to compare versions (are Workshop files missing?)..
        /// </summary>
        public static string VersionCheckFail {
            get {
                return ResourceManager.GetString("VersionCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBP Launcher in the RoN folder is the same as the downloaded Workshop version. Continuing....
        /// </summary>
        public static string VersionCheckSame {
            get {
                return ResourceManager.GetString("VersionCheckSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This window will close in 5 seconds..
        /// </summary>
        public static string WindowWillClose {
            get {
                return ResourceManager.GetString("WindowWillClose", resourceCulture);
            }
        }
    }
}
